# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11whB-zBWS51DJdpgp8RTGl0pZMHRwDOO
"""

!pip install transformers

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from transformers import AutoModel

models = [
    "bert-base-uncased",
    "roberta-base",
    "distilbert-base-uncased",
    "albert-base-v2",
    "google/electra-base-discriminator"
]

param_counts = []

for model_name in models:
    model = AutoModel.from_pretrained(model_name)
    total_params = sum(p.numel() for p in model.parameters())
    param_counts.append(total_params / 1e6)  # Convert to millions

param_counts

accuracy = [90.5, 92.4, 88.2, 89.6, 91.3]
f1_score = [89.8, 91.7, 87.9, 88.7, 90.4]

# Simulated inference time (relative comparison)
inference_time = [120, 140, 80, 100, 95]  # in ms

data = np.array([
    accuracy,
    f1_score,
    inference_time,
    param_counts
]).T

criteria = ["Accuracy", "F1 Score", "Inference Time", "Parameters (Millions)"]

df = pd.DataFrame(data, index=models, columns=criteria)
df

normalized = data / np.sqrt((data**2).sum(axis=0))
normalized

weights = np.array([0.35, 0.30, 0.20, 0.15])

weighted = normalized * weights
weighted

ideal_best = np.array([
    max(weighted[:,0]),   # Accuracy (max)
    max(weighted[:,1]),   # F1 (max)
    min(weighted[:,2]),   # Time (min)
    min(weighted[:,3])    # Parameters (min)
])

ideal_worst = np.array([
    min(weighted[:,0]),
    min(weighted[:,1]),
    max(weighted[:,2]),
    max(weighted[:,3])
])

S_plus = np.sqrt(((weighted - ideal_best)**2).sum(axis=1))
S_minus = np.sqrt(((weighted - ideal_worst)**2).sum(axis=1))

topsis_score = S_minus / (S_plus + S_minus)

# Create full result dataframe in required format
final_df = pd.DataFrame({
    "Model": models,
    "Parameters (M)": param_counts,
    "Inference Time (s)": inference_time,
    "Accuracy": accuracy,
    "F1 Score": f1_score,
    "TOPSIS Score": topsis_score
})

# Rank (Higher score = better)
final_df["Rank"] = final_df["TOPSIS Score"].rank(ascending=False)

# Sort by rank
final_df = final_df.sort_values(by="Rank")

final_df

final_df.to_csv("topsis_results.csv", index=False)

plt.figure()
plt.bar(final_df["Model"], final_df["TOPSIS Score"])
plt.xlabel("Models")
plt.ylabel("TOPSIS Score")
plt.title("TOPSIS Ranking of HuggingFace Text Classification Models")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("results_graph.png")
plt.show()